### PR TITLE
add datetime before log message

### PR DESCRIPTION
**Pull request by Ivendrakeo**
# Date

Initial PR Date:

Due Date:
4-20-21

# Reviewers

@anthony-bartman 

# Description

add's a timestamp before the log message. (for display on web-ui)
the format is: `04/14/21 11:53:55` 
an example message could then be the following: `04/14/21 11:53:55 Hello World!`

# Project Issue

# Test Results

sent a message to the log and verified the time shows up.

### CODE REVIEW

**Comment by Ivendrakeo** [comment]
@anthony-bartman is the time format good for you? id you suggest I change it to some other format, it shouldn't be too hard...

**Comment by anthony-bartman** [comment]
@Ivendrakeo  Could you make it so that the date is like only `month-day`? That's what I have currently and I think that would look nicer. And if that is an easy fix, I think that works for me. Should be easy to push to master than to pull into my logging-webxD branch.

**Comment by Ivendrakeo** [comment]
@rockboynton @anthony-bartman @iliescua what do you think? is `month-day` what the user would want? from my perspective, what if you want to log things hourly or better yet you want to know the exact timestamp where things went wrong. ie: your toaster failed at 10:32AM, 2 hrs after you left rather than just 4-14. I'm open to suggestions, but initially i included the exact time because i thought both pieces of information would be relevant.

**Comment by anthony-bartman** [comment]
@Ivendrakeo oh my bad I meant, that I want it to be like this `month-day  hour:minute:second`

**Comment by Ivendrakeo** [comment]
> @Ivendrakeo oh my bad I meant, that I want it to be like this `month-day hour:minute:second`

Ok I see now. I just changed it.

**Pull request merged**
