### PR TITLE
Add currently used programs attribute to pin conf

### PR DESCRIPTION
**Pull request by rockboynton**
# Date

Initial PR Date:

Due Date:

# Reviewers

@Ivendrakeo 
@anthony-bartman 

# Description

This adds a list of currently used programs for a pin.
The list is appended to when another program wants to use it

The "in_use" attribute is now no longer in use. Programs are
considered unused when no programs are using them

# Project Issue

# Test Results

Needs verification

### CODE REVIEW

**Comment by Ivendrakeo** [comment]
@rockboynton we good to merge this? The only thing i am concerned about is only one of the programs was being added to the pin config. is this an issue on master as well?

**Comment by rockboynton** [comment]
> @rockboynton we good to merge this? The only thing i am concerned about is only one of the programs was being added to the pin config. is this an issue on master as well?

it's a pretty big issue I think...it wasn't a problem before. Maybe you could check it out? I can't until tomorrow

**Comment by anthony-bartman** [comment]
@rockboynton  @Ivendrakeo  We good to merge this?

**Comment by anthony-bartman** [comment]
@rockboynton @Ivendrakeo  When we gonna merge and finish this? Friday?

**Pull request merged**
